# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AcquirerResponseCode.create(code: "0000", description: "Success", message: "Sucesso")
AcquirerResponseCode.create(code: "1000", description: "Do not honour", message: "Não aprovado")
AcquirerResponseCode.create(code: "1001", description: "Expired card", message: "Cartão vencido")
AcquirerResponseCode.create(code: "1002", description: "Suspected fraud", message: "Suspeita de fraude")
AcquirerResponseCode.create(code: "1003", description: "Card acceptor contact acquirer", message: "Estabelecimento entrar em contato com emissor")
AcquirerResponseCode.create(code: "1004", description: "Restricted card", message: "Cartão com restrição")
AcquirerResponseCode.create(code: "1005", description: "Card acceptor call acquirer's security department", message: "Estabelecimento entrar em contato com departamento de segurança do adquirente")
AcquirerResponseCode.create(code: "1006", description: "Allowable PIN tries exceeded", message: "Tentativas de senha excedidas")
AcquirerResponseCode.create(code: "1007", description: "Refer to card issuer", message: "Consultar o emissor")
AcquirerResponseCode.create(code: "1008", description: "Refer to card issuer's special conditions", message: "Consultar as condições especiais do emissor")
AcquirerResponseCode.create(code: "1009", description: "Invalid card acceptor", message: "Estabelecimento inválido")
AcquirerResponseCode.create(code: "1010", description: "Invalid amount", message: "Valor inválido")
AcquirerResponseCode.create(code: "1011", description: "Invalid card number", message: "Cartão inválido")
AcquirerResponseCode.create(code: "1012", description: "PIN data required", message: "Senha necessária")
AcquirerResponseCode.create(code: "1014", description: "No account of type requested", message: "Nenhuma conta do tipo selecionado")
AcquirerResponseCode.create(code: "1015", description: "Requested function not supported", message: "Função selecionada não suportada")
AcquirerResponseCode.create(code: "1016", description: "Not sufficient funds", message: "Saldo insuficiente")
AcquirerResponseCode.create(code: "1017", description: "Incorrect PIN", message: "Senha inválida")
AcquirerResponseCode.create(code: "1019", description: "Transaction not permitted to cardholder", message: "Transação não permitida para o portador")
AcquirerResponseCode.create(code: "1020", description: "Transaction not permitted to terminal", message: "Transação não permitida para o terminal")
AcquirerResponseCode.create(code: "1021", description: "Exceeds withdrawal amount limit", message: "Limite de valor para saque excedido")
AcquirerResponseCode.create(code: "1022", description: "Security violation", message: "Violação de segurança")
AcquirerResponseCode.create(code: "1023", description: "Exceeds withdrawal frequency limit", message: "Limite de quantidade de saques excedido")
AcquirerResponseCode.create(code: "1024", description: "Violation of law", message: "Violação da lei")
AcquirerResponseCode.create(code: "1025", description: "Card not effective", message: "Cartão bloqueado")
AcquirerResponseCode.create(code: "1026", description: "Invalid PIN block", message: "Dados de senha inválidos")
AcquirerResponseCode.create(code: "1027", description: "PIN length error", message: "Erro no tamanho da senha")
AcquirerResponseCode.create(code: "1028", description: "PIN key sync error", message: "Erro de sincronia de chave de senha")
AcquirerResponseCode.create(code: "1029", description: "Suspected counterfeit card", message: "Suspeita de cartão falso")
AcquirerResponseCode.create(code: "1030", description: "Currency unacceptable to card issuer", message: "Moeda inaceitável para o emissor")
AcquirerResponseCode.create(code: "1032", description: "Lost/stolen card", message: "Cartão perdido ou roubado")
AcquirerResponseCode.create(code: "1035", description: "Closed account", message: "Conta encerrada")
AcquirerResponseCode.create(code: "1036", description: "Closed savings account, or restricted for closing", message: "Conta poupança encerrada ou bloqueada para encerramento")
AcquirerResponseCode.create(code: "1037", description: "Closed credit account or restricted for closing", message: "Conta de crédito encerrada ou bloqueada para encerramento")
AcquirerResponseCode.create(code: "1039", description: "Closed cheque account or restricted for closing", message: "Conta corrente encerrada ou bloquada para encerramento")
AcquirerResponseCode.create(code: "1041", description: "From account bad status", message: "Status ruim para conta de origem")
AcquirerResponseCode.create(code: "1042", description: "To account bad status", message: "Status ruim para conta de destino")
AcquirerResponseCode.create(code: "1045", description: "Card verification data failed", message: "Código de segurança inválido")
AcquirerResponseCode.create(code: "1047", description: "PIN change required", message: "Troca de senha necessária")
AcquirerResponseCode.create(code: "1048", description: "New PIN invalid", message: "Nova senha inválida")
AcquirerResponseCode.create(code: "1057", description: "Payment date invalid", message: "Data de pagamento inválida")
AcquirerResponseCode.create(code: "1060", description: "Transaction did not complete normally at terminal", message: "Transação não completou normalmente no terminal")
AcquirerResponseCode.create(code: "1061", description: "Transaction not supported by the card issuer", message: "Transação não suportada pelo emissor")
AcquirerResponseCode.create(code: "1062", description: "Cashback not allowed", message: "Saque fácil não disponível")
AcquirerResponseCode.create(code: "1063", description: "Cashback amount exceeded", message: "Limite de saque fácil excedido")
AcquirerResponseCode.create(code: "1064", description: "Declined, transaction processed offline by terminal", message: "Negado offline pelo terminal")
AcquirerResponseCode.create(code: "1065", description: "Declined, terminal unable to process offline", message: "Negado, não foi possível processar offline")
AcquirerResponseCode.create(code: "2000", description: "Do not honour", message: "Não aprovado")
AcquirerResponseCode.create(code: "2001", description: "Expired card", message: "Cartão vencido")
AcquirerResponseCode.create(code: "2002", description: "Suspected fraud", message: "Suspeita de fraude")
AcquirerResponseCode.create(code: "2003", description: "Card acceptor contact acquirer", message: "Estabelecimento entrar em contato com emissor")
AcquirerResponseCode.create(code: "2004", description: "Restricted card", message: "Cartão com restrição")
AcquirerResponseCode.create(code: "2005", description: "Card acceptor call acquirer's security department", message: "Estabelecimento entrar em contato com departamento de segurança do adquirente")
AcquirerResponseCode.create(code: "2006", description: "Allowable PIN tries exceeded", message: "Tentativas de senha excedidas")
AcquirerResponseCode.create(code: "2007", description: "Special conditions", message: "Condições especiais")
AcquirerResponseCode.create(code: "2008", description: "Lost card", message: "Cartão perdido")
AcquirerResponseCode.create(code: "2009", description: "Stolen card", message: "Cartão roubado")
AcquirerResponseCode.create(code: "2010", description: "Suspected counterfeit card", message: "Suspeita de cartão falso")
AcquirerResponseCode.create(code: "2011", description: "Daily withdrawal uses exceeded", message: "Limite de quantidade de saques excedido")
AcquirerResponseCode.create(code: "2012", description: "Daily withdrawal amount exceeded", message: "Limite de valor para saque excedido")
AcquirerResponseCode.create(code: "9100", description: "One or more data element errors (see message error indicator)", message: "Erro no formato da mensagem")
AcquirerResponseCode.create(code: "9102", description: "Invalid transaction", message: "Transação inválida")
AcquirerResponseCode.create(code: "9103", description: "Re-enter transaction", message: "Tente novamente")
AcquirerResponseCode.create(code: "9105", description: "Acquirer not supported by switch", message: "Adquirente não suportado pelo switch")
AcquirerResponseCode.create(code: "9107", description: "Card issuer or switch inoperative", message: "Emissor fora de operação")
AcquirerResponseCode.create(code: "9108", description: "Transaction destination cannot be found for routing", message: "Não foi possível enviar a transação para o destinatário")
AcquirerResponseCode.create(code: "9109", description: "System malfunction", message: "Erro no sistema")
AcquirerResponseCode.create(code: "9110", description: "Card issuer signed off", message: "Emissor se desconectou")
AcquirerResponseCode.create(code: "9111", description: "Card issuer timed out", message: "Emissor não respondeu em tempo")
AcquirerResponseCode.create(code: "9112", description: "Card issuer unavailable", message: "Emissor indisponível")
AcquirerResponseCode.create(code: "9113", description: "Duplicate transmission", message: "Transmissão duplicada")
AcquirerResponseCode.create(code: "9114", description: "Not able to trace back to original transaction", message: "Não foi possível encontrar a transação original")
AcquirerResponseCode.create(code: "9116", description: "MAC incorrect", message: "MAC incorreto")
AcquirerResponseCode.create(code: "9117", description: "MAC key sync error", message: "Erro de sincronização de chave de MAC")
AcquirerResponseCode.create(code: "9118", description: "No communication keys available for use", message: "Nenhuma chave de comunicação disponível")
AcquirerResponseCode.create(code: "9119", description: "Encryption key sync error", message: "Erro de sincronização de chave de encriptação")
AcquirerResponseCode.create(code: "9120", description: "Security software/hardware error – try again", message: "Erro de segurança de software/hardware, tente novamente")
AcquirerResponseCode.create(code: "9121", description: "Security software/hardware error – no action", message: "Erro de segurança de software/hardware")
AcquirerResponseCode.create(code: "9122", description: "Message number out of sequence", message: "Número da mensagem fora de sequência")
AcquirerResponseCode.create(code: "9123", description: "Request in progress", message: "Requisição em progresso")
AcquirerResponseCode.create(code: "9124", description: "Invalid security code", message: "Código de segurança inválido")
AcquirerResponseCode.create(code: "9125", description: "Database error", message: "Erro no banco de dados")
AcquirerResponseCode.create(code: "9132", description: "Recurring data error", message: "Erro nos dados de recorrência")
AcquirerResponseCode.create(code: "9133", description: "Update not allowed", message: "Atualização não permitida")
AcquirerResponseCode.create(code: "9350", description: "Violation of business arrangement", message: "Violação de acordo comercial")
AcquirerResponseCode.create(code: "9999", description: "Other errors", message: "Erro não especificado")
AcquirerResponseCode.create(code: "UNPR", description: "Rejection", message: "Não Foi possível processar – Não foi possível processar a mensagem. Tente novamente.")
AcquirerResponseCode.create(code: "IMSG", description: "Rejection", message: "Mensagem Invalida – A mensagem enviada possui um formato inválido.")
AcquirerResponseCode.create(code: "PARS", description: "Rejection", message: "Erro na leitura da mensagem – Algum campo obrigatório não esta sendo enviado")
AcquirerResponseCode.create(code: "SECU", description: "Rejection", message: "Segurança – Algum erro no processo de segurança. A chave de criptografia pode não estar presente no terminal.")
AcquirerResponseCode.create(code: "INTP", description: "Rejection", message: "SAK Invalido – O SAK enviado não foi reconhecido")
AcquirerResponseCode.create(code: "RCPP", description: "Rejection", message: "Destinatario Invalido – O local para aonde a mensagem foi enviada esta invalida")
AcquirerResponseCode.create(code: "DPMG", description: "Rejection", message: "Mensagem Duplicada – Esta mensagem já foi recebida pela Stone.")
AcquirerResponseCode.create(code: "VERS", description: "Rejection", message: "Protocolo – A versão do protocolo enviada não é suportada.")
AcquirerResponseCode.create(code: "MSGT", description: "Rejection", message: "Tipo da Mensagem – o Message Type enviado não é reconhecido.")